version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run:
          name: Install dependencies for the node project and builds it
          command: npm install && npm run build
      - run:
          name: Install MinIO S3 management tool
          command: |
            wget https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x mc &&
            mc alias set virtuatable ${BS_ENDPOINT} ${BS_ACCESS_KEY} ${BS_SECRET_KEY} &&
            mc cp --recursive dist/ virtuatable/auth-gui/$(data +%s)

workflows:
  build:
    jobs:
      - build